services:
  backend:
    build:
      context: .
      dockerfile: ./docker/build/php.dockerfile
    container_name: php
    working_dir: /var/www
    user: "root"
    volumes:
      - ./symfony:/var/www
      - ./docker/conf/backend/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./docker/conf/backend/messenger.conf:/etc/supervisor/conf.d/messenger.conf
    networks:
      - internal
    restart: unless-stopped
    tty: true
    stdin_open: true

  db:
    image: postgres:18-alpine
    container_name: postgres
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/conf/db/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DB:-app}'"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  internal:
    driver: bridge

volumes:
  postgres-data: