framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # Не привязываюсь к сущности post. Возможно следует сделать отдельный транспорт для post
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    table_name: messages
                    queue_name: default
                retry_strategy:
                    max_retries: 10
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            async_failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    table_name: failed_messages
                    queue_name: failed

        failure_transport: async_failed

        routing:
            # Route your messages to the transports
            'App\Message\GetPostDetailMessage': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
