parameters:
    env(CONSUMER_ID): '0'

framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # Не привязываюсь к сущности post. Возможно следует сделать отдельный транспорт для post
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    stream: 'messenger_messages'
                    group: 'application'
                    consumer: 'consumer-%env(CONSUMER_ID)%'
                    delete_after_ack: true
                    auto_setup: true
                    lazy: false
                retry_strategy:
                    max_retries: 10
                    delay: 100000
                    multiplier: 1.2
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            async_failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_FAILED)%'

        failure_transport: async_failed

        routing:
            # Route your messages to the transports
            'App\Message\GetPostDetailBatchMessage': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
