parameters:
    # Все прокси для ip адреса моего компа, поэтому норм
    http_proxy_list:
        - 104.207.52.63:3129
        - 216.26.248.143:3129
        - 209.50.161.38:3129
        - 216.26.243.55:3129
        - 45.3.34.97:3129
        - 45.3.44.63:3129
        - 209.50.167.64:3129
        - 209.50.177.113:3129
        - 193.56.28.229:3129
        - 104.207.32.61:3129
        - 216.26.251.248:3129
        - 65.111.11.110:3129
        - 45.3.47.231:3129
        - 45.3.38.33:3129
        - 216.26.238.220:3129
        - 45.3.51.214:3129
        - 65.111.20.121:3129
        - 154.213.160.66:3129
        - 45.3.48.166:3129
        - 209.50.170.35:3129
        - 216.26.241.207:3129
        - 209.50.185.150:3129
        - 65.111.28.137:3129
        - 216.26.231.231:3129
        - 45.3.40.32:3129
        - 65.111.1.23:3129
        - 216.26.233.94:3129
        - 104.207.46.230:3129
        - 104.167.25.224:3129
        - 104.207.41.125:3129
        - 209.50.171.37:3129
        - 65.111.0.107:3129
        - 65.111.9.234:3129
        - 65.111.22.134:3129
        - 154.213.164.71:3129
        - 104.207.41.60:3129
        - 45.3.54.83:3129
        - 216.26.243.190:3129
        - 65.111.29.65:3129
        - 209.50.166.84:3129
        - 209.50.175.155:3129
        - 104.207.42.33:3129
        - 45.3.32.178:3129
        - 104.207.56.202:3129
        - 209.50.168.104:3129
        - 216.26.253.186:3129
        - 216.26.233.222:3129
        - 45.3.51.207:3129
        - 65.111.8.85:3129
        - 209.50.182.122:3129
        - 104.207.48.254:3129
        - 65.111.7.119:3129
        - 45.3.53.164:3129
        - 45.3.35.93:3129
        - 45.3.62.151:3129
        - 65.111.29.211:3129
        - 65.111.7.214:3129
        - 209.50.171.122:3129
        - 104.207.46.50:3129
        - 216.26.237.132:3129
        - 209.50.188.233:3129
        - 104.167.19.135:3129
        - 216.26.236.99:3129
        - 65.111.8.154:3129
        - 209.50.184.27:3129
        - 216.26.241.211:3129
        - 216.26.233.172:3129
        - 209.50.183.87:3129
        - 209.50.165.237:3129
        - 154.213.164.158:3129
        - 45.3.32.99:3129
        - 216.26.230.214:3129
        - 45.3.51.135:3129
        - 65.111.24.196:3129
        - 209.50.173.3:3129
        - 216.26.240.156:3129
        - 45.3.39.88:3129
        - 104.207.35.5:3129
        - 104.167.19.12:3129
        - 45.3.55.0:3129
        - 65.111.28.58:3129
        - 65.111.3.4:3129
        - 154.213.161.182:3129
        - 65.111.11.202:3129
        - 216.26.246.94:3129
        - 209.50.163.232:3129
        - 104.207.62.89:3129
        - 65.111.6.46:3129
        - 104.207.58.255:3129
        - 216.26.237.69:3129
        - 209.50.187.227:3129
        - 216.26.245.94:3129
        - 104.207.58.215:3129
        - 104.207.62.3:3129
        - 65.111.30.228:3129
        - 209.50.168.161:3129
        - 45.3.44.0:3129
        - 65.111.26.192:3129
        - 216.26.224.15:3129
        - 45.3.51.156:3129
