parameters:
    # Все прокси для ip адреса моего компа, поэтому норм
    http_proxy_list:
        - 216.26.241.18:3129
        - 209.50.186.16:3129
        - 209.50.160.38:3129
        - 65.111.9.168:3129
        - 65.111.30.241:3129
        - 65.111.11.230:3129
        - 104.207.60.237:3129
        - 104.167.19.13:3129
        - 104.207.52.15:3129
        - 65.111.21.194:3129
        - 65.111.14.25:3129
        - 45.3.52.129:3129
        - 216.26.253.254:3129
        - 65.111.8.200:3129
        - 45.3.51.92:3129
        - 216.26.238.209:3129
        - 45.3.44.231:3129
        - 45.3.50.201:3129
        - 104.207.55.139:3129
        - 104.207.49.212:3129
        - 104.207.37.81:3129
        - 209.50.177.255:3129
        - 65.111.27.124:3129
        - 65.111.3.165:3129
        - 45.3.42.241:3129
        - 45.3.36.213:3129
        - 209.50.164.136:3129
        - 65.111.25.191:3129
        - 209.50.166.134:3129
        - 209.50.161.48:3129
        - 104.207.63.222:3129
        - 45.3.49.155:3129
        - 45.3.53.250:3129
        - 209.50.160.1:3129
        - 104.207.42.85:3129
        - 209.50.178.88:3129
        - 209.50.166.233:3129
        - 65.111.0.100:3129
        - 65.111.3.167:3129
        - 104.207.33.109:3129
        - 45.3.51.246:3129
        - 45.3.32.114:3129
        - 104.207.34.76:3129
        - 209.50.185.202:3129
        - 104.207.55.153:3129
        - 45.3.32.252:3129
        - 154.213.160.159:3129
        - 65.111.3.215:3129
        - 45.3.62.174:3129
        - 104.207.45.51:3129
        - 45.3.55.189:3129
        - 104.207.38.44:3129
        - 209.50.176.161:3129
        - 209.50.177.128:3129
        - 209.50.188.33:3129
        - 104.207.38.137:3129
        - 209.50.182.197:3129
        - 104.207.44.174:3129
        - 104.207.39.77:3129
        - 45.3.52.41:3129
        - 104.207.36.206:3129
        - 209.50.178.18:3129
        - 45.3.44.112:3129
        - 216.26.249.191:3129
        - 209.50.168.171:3129
        - 193.56.28.182:3129
        - 65.111.0.43:3129
        - 104.207.58.230:3129
        - 104.207.33.13:3129
        - 216.26.252.241:3129
        - 154.213.163.4:3129
        - 65.111.12.168:3129
        - 209.50.183.97:3129
        - 216.26.233.82:3129
        - 104.207.51.198:3129
        - 209.50.166.2:3129
        - 216.26.255.11:3129
        - 65.111.24.49:3129
        - 65.111.3.23:3129
        - 216.26.247.166:3129
        - 45.3.39.167:3129
        - 65.111.28.83:3129
        - 216.26.228.191:3129
        - 209.50.168.36:3129
        - 216.26.229.83:3129
        - 209.50.176.51:3129
        - 45.3.55.130:3129
        - 65.111.3.44:3129
        - 104.207.35.105:3129
        - 65.111.26.141:3129
        - 45.3.37.255:3129
        - 209.50.162.228:3129
        - 209.50.164.93:3129
        - 209.50.184.16:3129
        - 209.50.166.224:3129
        - 104.207.40.81:3129
        - 104.207.62.3:3129
        - 216.26.224.172:3129
        - 45.3.40.29:3129
        - 104.207.45.42:3129
