parameters:
    # Все прокси для ip адреса моего компа, поэтому норм
    http_proxy_list:
       - 65.111.12.135:3129
       - 45.3.50.242:3129
       - 104.207.49.93:3129
       - 104.207.42.148:3129
       - 216.26.251.89:3129
       - 104.207.45.54:3129
       - 104.207.45.78:3129
       - 209.50.164.88:3129
       - 65.111.26.173:3129
       - 209.50.176.213:3129
       - 65.111.25.214:3129
       - 104.207.33.51:3129
       - 45.3.46.124:3129
       - 216.26.247.160:3129
       - 104.167.25.186:3129
       - 104.207.44.195:3129
       - 104.207.35.230:3129
       - 65.111.27.119:3129
       - 209.50.161.101:3129
       - 104.207.62.97:3129
       - 45.3.49.138:3129
       - 45.3.38.199:3129
       - 104.207.40.137:3129
       - 104.207.50.140:3129
       - 45.3.55.183:3129
       - 45.3.36.45:3129
       - 65.111.29.60:3129
       - 209.50.174.138:3129
       - 65.111.7.193:3129
       - 45.3.42.184:3129
       - 154.213.160.89:3129
       - 104.207.56.186:3129
       - 65.111.22.125:3129
       - 193.56.28.126:3129
       - 216.26.228.34:3129
       - 45.3.47.144:3129
       - 209.50.186.159:3129
       - 65.111.31.54:3129
       - 209.50.187.210:3129
       - 216.26.248.160:3129
       - 65.111.11.177:3129
       - 104.207.37.55:3129
       - 193.56.28.246:3129
       - 45.3.39.240:3129
       - 209.50.173.93:3129
       - 104.207.33.164:3129
       - 209.50.180.254:3129
       - 65.111.14.15:3129
       - 65.111.27.139:3129
       - 45.3.39.232:3129
       - 45.3.34.177:3129
       - 209.50.166.20:3129
       - 216.26.245.208:3129
       - 104.207.60.241:3129
       - 45.3.51.194:3129
       - 209.50.173.196:3129
       - 104.207.61.69:3129
       - 216.26.239.52:3129
       - 209.50.183.171:3129
       - 45.3.40.251:3129
       - 104.207.49.159:3129
       - 45.3.43.99:3129
       - 65.111.20.70:3129
       - 45.3.32.101:3129
       - 104.207.48.3:3129
       - 209.50.182.214:3129
       - 104.207.42.140:3129
       - 45.3.49.229:3129
       - 216.26.226.141:3129
       - 209.50.191.133:3129
       - 104.207.46.30:3129
       - 209.50.184.146:3129
       - 45.3.54.135:3129
       - 104.207.32.16:3129
       - 104.167.25.14:3129
       - 65.111.28.142:3129
       - 104.207.40.20:3129
       - 216.26.247.105:3129
       - 209.50.172.9:3129
       - 154.213.166.5:3129
       - 65.111.30.212:3129
       - 65.111.27.58:3129
       - 209.50.161.95:3129
       - 209.50.163.30:3129
       - 65.111.31.247:3129
       - 209.50.165.246:3129
       - 216.26.239.171:3129
       - 45.3.48.75:3129
       - 65.111.6.155:3129
       - 216.26.236.136:3129
       - 45.3.37.125:3129
       - 216.26.243.27:3129
       - 45.3.50.173:3129
       - 104.207.40.72:3129
       - 216.26.254.59:3129
       - 209.50.185.101:3129
       - 216.26.237.199:3129
       - 65.111.1.14:3129
       - 104.207.35.65:3129
       - 65.111.6.79:3129

