parameters:
    # Все прокси для ip адреса моего компа, поэтому норм
    http_proxy_list:
        - 104.207.60.230:3129
        - 104.207.60.97:3129
        - 45.3.40.172:3129
        - 45.3.36.255:3129
        - 104.207.56.173:3129
        - 209.50.180.62:3129
        - 104.207.42.152:3129
        - 216.26.234.33:3129
        - 216.26.242.17:3129
        - 216.26.246.255:3129
        - 104.207.55.90:3129
        - 45.3.48.124:3129
        - 65.111.27.156:3129
        - 209.50.170.133:3129
        - 45.3.48.203:3129
        - 216.26.247.84:3129
        - 216.26.238.214:3129
        - 104.167.19.72:3129
        - 209.50.172.77:3129
        - 154.213.161.243:3129
        - 216.26.229.94:3129
        - 45.3.45.9:3129
        - 209.50.161.126:3129
        - 65.111.5.37:3129
        - 45.3.49.158:3129
        - 45.3.43.69:3129
        - 104.207.48.37:3129
        - 209.50.173.250:3129
        - 104.207.34.252:3129
        - 65.111.14.52:3129
        - 216.26.231.205:3129
        - 45.3.42.0:3129
        - 209.50.191.146:3129
        - 104.207.58.253:3129
        - 209.50.189.121:3129
        - 45.3.44.142:3129
        - 209.50.169.129:3129
        - 45.3.49.0:3129
        - 209.50.168.190:3129
        - 45.3.48.253:3129
        - 45.3.53.56:3129
        - 45.3.45.183:3129
        - 154.213.165.58:3129
        - 65.111.25.84:3129
        - 216.26.229.56:3129
        - 104.207.47.104:3129
        - 45.3.41.156:3129
        - 104.207.46.12:3129
        - 65.111.10.229:3129
        - 65.111.6.116:3129
        - 104.207.51.138:3129
        - 104.207.55.155:3129
        - 104.207.57.10:3129
        - 209.50.169.156:3129
        - 104.207.41.183:3129
        - 45.3.34.54:3129
        - 104.207.32.48:3129
        - 65.111.4.151:3129
        - 216.26.227.131:3129
        - 104.207.58.153:3129
        - 209.50.173.222:3129
        - 104.207.50.39:3129
        - 216.26.249.160:3129
        - 65.111.12.230:3129
        - 65.111.11.25:3129
        - 216.26.243.69:3129
        - 216.26.252.144:3129
        - 209.50.164.30:3129
        - 45.3.51.112:3129
        - 209.50.191.226:3129
        - 209.50.170.82:3129
        - 104.207.42.141:3129
        - 104.207.46.84:3129
        - 209.50.180.236:3129
        - 104.207.60.116:3129
        - 45.3.53.239:3129
        - 216.26.224.43:3129
        - 45.3.37.244:3129
        - 104.207.48.234:3129
        - 104.207.53.9:3129
        - 209.50.184.180:3129
        - 154.213.166.24:3129
        - 216.26.231.24:3129
        - 65.111.0.51:3129
        - 104.207.50.158:3129
        - 104.207.58.90:3129
        - 209.50.188.193:3129
        - 193.56.28.54:3129
        - 45.3.44.173:3129
        - 45.3.34.164:3129
        - 65.111.11.252:3129
        - 216.26.237.192:3129
        - 65.111.30.21:3129
        - 216.26.235.145:3129
        - 45.3.40.141:3129
        - 216.26.240.159:3129
        - 209.50.187.98:3129
        - 193.56.28.139:3129
        - 45.3.53.182:3129
        - 45.3.47.14:3129
