parameters:
    # Все прокси для ip адреса моего компа, поэтому норм
    http_proxy_list:
        - 216.26.225.148:3129
        - 104.207.59.254:3129
        - 45.3.44.43:3129
        - 65.111.2.31:3129
        - 209.50.167.235:3129
        - 104.207.55.204:3129
        - 154.213.164.4:3129
        - 65.111.7.94:3129
        - 216.26.235.68:3129
        - 209.50.160.40:3129
        - 65.111.29.154:3129
        - 209.50.172.138:3129
        - 65.111.20.153:3129
        - 209.50.180.159:3129
        - 216.26.227.243:3129
        - 216.26.227.13:3129
        - 45.3.52.9:3129
        - 65.111.12.180:3129
        - 104.207.59.239:3129
        - 104.207.47.209:3129
        - 216.26.232.89:3129
        - 45.3.36.104:3129
        - 104.207.38.246:3129
        - 216.26.254.70:3129
        - 209.50.162.232:3129
        - 209.50.184.213:3129
        - 154.213.162.184:3129
        - 209.50.160.170:3129
        - 216.26.230.175:3129
        - 216.26.244.146:3129
        - 209.50.165.78:3129
        - 216.26.240.221:3129
        - 216.26.235.216:3129
        - 216.26.253.236:3129
        - 209.50.178.16:3129
        - 216.26.228.193:3129
        - 104.207.63.0:3129
        - 216.26.254.1:3129
        - 45.3.33.192:3129
        - 45.3.46.181:3129
        - 45.3.41.7:3129
        - 154.213.162.128:3129
        - 216.26.249.232:3129
        - 45.3.50.32:3129
        - 65.111.27.107:3129
        - 216.26.233.113:3129
        - 104.207.55.44:3129
        - 65.111.2.7:3129
        - 45.3.53.152:3129
        - 104.207.57.186:3129
        - 45.3.45.125:3129
        - 65.111.6.0:3129
        - 209.50.171.17:3129
        - 154.213.164.59:3129
        - 209.50.181.240:3129
        - 65.111.1.194:3129
        - 216.26.239.137:3129
        - 209.50.177.56:3129
        - 45.3.41.127:3129
        - 216.26.237.234:3129
        - 104.207.52.127:3129
        - 104.207.40.171:3129
        - 209.50.177.123:3129
        - 216.26.243.68:3129
        - 65.111.29.88:3129
        - 65.111.27.251:3129
        - 216.26.231.48:3129
        - 104.207.51.196:3129
        - 104.207.33.165:3129
        - 209.50.190.65:3129
        - 216.26.226.170:3129
        - 216.26.237.113:3129
        - 209.50.183.252:3129
        - 65.111.1.6:3129
        - 209.50.182.40:3129
        - 209.50.190.99:3129
        - 209.50.183.226:3129
        - 104.207.41.182:3129
        - 216.26.247.96:3129
        - 45.3.62.248:3129
        - 104.207.38.156:3129
        - 209.50.162.161:3129
        - 45.3.34.18:3129
        - 209.50.171.96:3129
        - 104.207.52.229:3129
        - 45.3.48.121:3129
        - 209.50.179.242:3129
        - 216.26.253.55:3129
        - 209.50.189.39:3129
        - 65.111.13.78:3129
        - 216.26.252.123:3129
        - 209.50.185.75:3129
        - 45.3.37.72:3129
        - 209.50.170.10:3129
        - 154.213.166.135:3129
        - 209.50.164.165:3129
        - 104.207.44.188:3129
        - 104.207.60.129:3129
        - 209.50.170.160:3129
        - 104.207.33.220:3129
