parameters:
    # Все прокси для ip адреса моего компа, поэтому норм
    http_proxy_list:
        - 65.111.21.214:3129
        - 65.111.22.203:3129
        - 65.111.4.86:3129
        - 216.26.228.104:3129
        - 209.50.172.246:3129
        - 154.213.164.112:3129
        - 216.26.235.249:3129
        - 216.26.248.62:3129
        - 104.207.32.159:3129
        - 65.111.10.215:3129
        - 65.111.3.216:3129
        - 45.3.40.68:3129
        - 45.3.39.110:3129
        - 104.207.33.198:3129
        - 45.3.52.251:3129
        - 216.26.235.46:3129
        - 193.56.28.213:3129
        - 216.26.247.75:3129
        - 209.50.162.131:3129
        - 154.213.162.242:3129
        - 65.111.0.186:3129
        - 104.207.45.175:3129
        - 216.26.232.240:3129
        - 45.3.35.85:3129
        - 45.3.52.15:3129
        - 45.3.33.66:3129
        - 209.50.172.136:3129
        - 104.207.58.87:3129
        - 216.26.249.221:3129
        - 45.3.47.18:3129
        - 209.50.176.39:3129
        - 209.50.181.21:3129
        - 209.50.175.46:3129
        - 65.111.2.47:3129
        - 104.207.48.66:3129
        - 104.207.62.84:3129
        - 216.26.228.27:3129
        - 65.111.14.144:3129
        - 104.207.42.18:3129
        - 104.207.52.178:3129
        - 209.50.168.205:3129
        - 154.213.162.21:3129
        - 216.26.234.68:3129
        - 104.207.57.96:3129
        - 104.207.34.140:3129
        - 65.111.3.208:3129
        - 45.3.42.59:3129
        - 45.3.39.163:3129
        - 216.26.235.18:3129
        - 216.26.229.254:3129
        - 216.26.232.228:3129
        - 154.213.161.165:3129
        - 65.111.10.85:3129
        - 154.213.166.86:3129
        - 216.26.251.111:3129
        - 209.50.176.104:3129
        - 45.3.55.166:3129
        - 104.207.36.69:3129
        - 65.111.6.44:3129
        - 65.111.25.81:3129
        - 45.3.43.72:3129
        - 216.26.248.110:3129
        - 104.207.55.0:3129
        - 65.111.24.201:3129
        - 216.26.244.54:3129
        - 104.207.39.182:3129
        - 216.26.234.214:3129
        - 209.50.176.112:3129
        - 216.26.242.248:3129
        - 104.167.19.212:3129
        - 216.26.234.229:3129
        - 216.26.230.90:3129
        - 209.50.187.73:3129
        - 65.111.23.227:3129
        - 216.26.227.116:3129
        - 216.26.227.98:3129
        - 154.213.162.165:3129
        - 65.111.27.206:3129
        - 154.213.165.156:3129
        - 104.207.50.248:3129
        - 65.111.28.12:3129
        - 104.167.25.89:3129
        - 104.167.19.141:3129
        - 209.50.167.244:3129
        - 216.26.235.250:3129
        - 65.111.22.229:3129
        - 45.3.55.81:3129
        - 45.3.51.66:3129
        - 209.50.190.164:3129
        - 209.50.161.231:3129
        - 45.3.38.128:3129
        - 216.26.238.150:3129
        - 209.50.181.149:3129
        - 65.111.7.85:3129
        - 209.50.184.176:3129
        - 65.111.2.82:3129
        - 216.26.248.102:3129
        - 216.26.229.109:3129
        - 45.3.62.23:3129
        - 45.3.54.191:3129
