parameters:
    # Все прокси для ip адреса моего компа, поэтому норм
    http_proxy_list:
        - 104.207.57.169:3129
        - 193.56.28.2:3129
        - 104.207.51.186:3129
        - 154.213.162.147:3129
        - 216.26.255.148:3129
        - 65.111.21.242:3129
        - 104.207.55.188:3129
        - 209.50.167.130:3129
        - 216.26.224.246:3129
        - 154.213.164.249:3129
        - 104.207.48.101:3129
        - 216.26.247.39:3129
        - 216.26.237.234:3129
        - 104.207.60.93:3129
        - 65.111.31.240:3129
        - 65.111.22.200:3129
        - 65.111.21.140:3129
        - 104.207.40.152:3129
        - 154.213.166.135:3129
        - 209.50.173.141:3129
        - 193.56.28.136:3129
        - 216.26.247.159:3129
        - 216.26.248.219:3129
        - 216.26.238.204:3129
        - 45.3.35.48:3129
        - 65.111.13.88:3129
        - 65.111.3.21:3129
        - 104.207.59.209:3129
        - 65.111.21.52:3129
        - 104.207.54.209:3129
        - 216.26.242.56:3129
        - 209.50.184.97:3129
        - 45.3.32.13:3129
        - 154.213.163.114:3129
        - 104.207.40.121:3129
        - 104.207.49.62:3129
        - 209.50.167.235:3129
        - 154.213.164.71:3129
        - 65.111.4.227:3129
        - 104.207.43.98:3129
        - 216.26.229.207:3129
        - 65.111.8.151:3129
        - 45.3.32.188:3129
        - 65.111.24.167:3129
        - 65.111.9.38:3129
        - 216.26.232.12:3129
        - 216.26.250.76:3129
        - 209.50.173.143:3129
        - 65.111.8.172:3129
        - 209.50.187.236:3129
        - 65.111.2.234:3129
        - 45.3.39.61:3129
        - 104.167.19.23:3129
        - 216.26.243.253:3129
        - 45.3.54.141:3129
        - 216.26.237.189:3129
        - 45.3.34.248:3129
        - 104.207.35.244:3129
        - 45.3.53.80:3129
        - 45.3.46.20:3129
        - 104.207.49.204:3129
        - 209.50.177.126:3129
        - 154.213.160.189:3129
        - 216.26.254.95:3129
        - 209.50.178.205:3129
        - 216.26.239.72:3129
        - 216.26.255.159:3129
        - 65.111.27.79:3129
        - 216.26.248.247:3129
        - 216.26.237.21:3129
        - 209.50.175.68:3129
        - 104.207.56.165:3129
        - 45.3.34.147:3129
        - 209.50.173.245:3129
        - 216.26.244.138:3129
        - 104.207.43.189:3129
        - 216.26.254.155:3129
        - 65.111.25.112:3129
        - 45.3.42.12:3129
        - 65.111.5.140:3129
        - 216.26.249.0:3129
        - 65.111.22.212:3129
        - 45.3.49.29:3129
        - 209.50.172.55:3129
        - 216.26.232.148:3129
        - 216.26.249.142:3129
        - 65.111.22.175:3129
        - 45.3.34.63:3129
        - 65.111.8.47:3129
        - 216.26.236.242:3129
        - 104.207.36.147:3129
        - 104.207.43.35:3129
        - 209.50.172.167:3129
        - 104.207.49.49:3129
        - 216.26.225.153:3129
        - 65.111.22.12:3129
        - 216.26.232.96:3129
        - 209.50.169.14:3129
        - 104.207.44.161:3129
        - 154.213.163.135:3129
